name = "StaticTools"
uuid = "86c06d3c-3f03-46de-9781-57580aa96d0a"
authors = ["C. Brenhin Keller and contributors"]
version = "0.2.0"

[deps]
ManualMemory = "d125e4d3-2237-4719-b19c-fa641b8a4667"

[compat]
julia = "1.8"
ManualMemory = "0.1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
